package org.zeroclick.configuration.shared.onboarding;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "org.zeroclick.configuration.onboarding.OnBoradingUserForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class OnBoradingUserFormData extends AbstractFormData {

	private static final long serialVersionUID = 1L;

	public Login getLogin() {
		return getFieldByClass(Login.class);
	}

	public TimeZone getTimeZone() {
		return getFieldByClass(TimeZone.class);
	}

	public UserId getUserId() {
		return getFieldByClass(UserId.class);
	}

	public static class Login extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class TimeZone extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class UserId extends AbstractValueFieldData<Long> {

		private static final long serialVersionUID = 1L;
	}
}
